development:
  adapter: postgresql
  encoding: unicode
  database: chat-app
  host: localhost
  pool: 5
  username: postgres
  password: 123456
  port: 5432
staging:
  adapter: postgresql
  encoding: unicode
  database: chat-app
  host: localhost
  pool: 5
  username: postgres
  password: 123456
  port: 5432
  